<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>fschathost</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Prelude.fs" />
    <Compile Include="AsyncUtil.fs" />
    <Compile Include="ChatTypes.fs" />
    <Compile Include="ChatUser.fs" />
    <Compile Include="AboutChannelActor.fs" />
    <Compile Include="GroupChatChannelActor.fs" />
    <Compile Include="ChatServer.fs" />
    <Compile Include="UserStore.fs" />
    <Compile Include="Diag.fs" />
    <Compile Include="Json.fs" />
    <Compile Include="../Client/Shared/ChatProtocol.fs" />
    <Compile Include="ProtocolConv.fs" />
    <Compile Include="SocketFlow.fs" />
    <Compile Include="UserSessionFlow.fs" />
    <Compile Include="Logon.fs" />
    <Compile Include="UserSession.fs" />
    <Compile Include="AppGiraffe.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Akkling" Version="0.14.0" />
    <PackageReference Include="Akkling.Streams" Version="0.14.0" />
    <PackageReference Include="Akkling.Persistence" Version="0.14.0" />
    <PackageReference Include="Akka.Persistence.Sqlite" Version="1.5.32" />
    <PackageReference Include="Giraffe" Version="6.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.0" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
    <PackageReference Include="Thoth.Json.Net" Version="12.0.0" />
    <PackageReference Remove="Fable.JsonConverter" />
  </ItemGroup>
</Project>